### DISCUSSION TITLE
config.yaml for d455 is not working. openvslam output is always resetting.

### DISCUSSION THREAD

**Discussion by Udaykiran87** [realsenseai/realsense-ros#1945] [Q&A]
Hello Community,
I am using intel realsense d455 depth camera for my robotic application.
I am using OpenVSLAM for mapping and navigation using ros2 by using rosbag file.

I am using below repository from OpenVSLAM for my application.
https://github.com/OpenVSLAM-Community/openvslam_ros/tree/wip/approximate-time-rgbd/src

I do not have much knowledge about how to create config.yaml file. I have referred [this](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/blob/ac3b14b851210cbfec28dab6383bc94ff9b32d0f/config/realsense_d455/right.yaml) and  [this](https://github.com/OpenVSLAM-Community/openvslam/blob/main/example/tum_rgbd/TUM_RGBD_rgbd_2.yaml) to create my config.yaml 
The issue is that my **openVSLAM output is resetting every few seconds (tracking is lost).** 

Could any one confirm if my config.yaml for d455 rgbd camera as mentioned below is correct or not? If not what is the wrong.

Could any one also explain me how focal_x_baseline, depth_threshold, depthmap_factor, baseline_dist_thr etc mentioned in the yaml file impacts on openvslam output? How to calculate these values for different realsense camera?
Any help would be really helpful to me.

Note: My rosbag shows color_image resolution as 1280x720 where as depth_image resolution as 848x480.

**My config.yaml is as below (output for which is resetting map (tracking is lost)every few seconds):**

```
#==============#
# Camera Model #
#==============#

Camera:
  name: "D455"
  setup: "RGBD"
  model: "perspective"

  fx: 387.47454833984375
  fy: 387.47454833984375
  cx: 316.1062927246094
  cy: 238.7586212158203

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  fps: 30.0
  cols: 1280
  rows: 720
  focal_x_baseline: 40.0

  color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature:
  max_num_keypoints: 1000
  ini_max_num_keypoints: 2000
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#=====================#
# Tracking Parameters #
#=====================#

depth_threshold: 40.0
depthmap_factor: 1.0

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr: 0.07471049682

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.05
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
  viewpoint_f: 400
```

But it works very well with tum_rgbd_fr2 dataset (without any reset problem). **The config.yaml used for tum_rgbd_fr2 dataset is as below**:

```
# TUM-RGBD RGBD model for 02

#==============#
# Camera Model #
#==============#

Camera:
  name: "TUM-RGBD RGBD 02"
  setup: "RGBD"
  model: "perspective"

  fx: 520.908620
  fy: 521.007327
  cx: 325.141442
  cy: 249.701764

  k1: 0.231222
  k2: -0.784899
  p1: -0.003257
  p2: -0.000105
  k3: 0.917205

  fps: 30.0
  cols: 640
  rows: 480
  focal_x_baseline: 40.0

  color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature:
  max_num_keypoints: 1000
  ini_max_num_keypoints: 2000
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#=====================#
# Tracking Parameters #
#=====================#

depth_threshold: 40.0
depthmap_factor: 1.0

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr: 0.07471049682

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.05
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
  viewpoint_f: 400
```

Thanks and Regards,
Udaykiran Patnaik.
