### ISSUE TITLE
running with docker

### ISSUE THREAD

**Issue by waspinator** [realsenseai/realsense-ros#1104]
I'm trying to run ros within docker containers, but I'm having issue passing through the realsense hardware paths because they contain colons. Can you reconfigure the device names to not contain colons?

```yaml
version: "3"

services:

  ros-master:
    image: ros:kinetic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  realsense:
    build:
      context: ./docker
      dockerfile: ros-realsense.dockerfile
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=realsense"
    devices:
      - "/dev/HID-SENSOR-2000e1.3.auto:/dev/HID-SENSOR-2000e1.3.auto"
      - "/dev/iio:device0:/dev/iio:device0"
      - "/dev/iio:device1:/dev/iio:device1"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
    networks:
      - ros
    restart: always
    command: roslaunch realsense2_camera rs_camera.launch


networks:
  ros:
    driver: bridge
```

**Comment by waspinator** [comment]
adding the `privileged: true` option and sharing all of `/dev` seems to be working...

```yaml
version: "3"

services:

  ros-master:
    image: ros:kinetic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always


  realsense:
    privileged: true
    build:
      context: ./docker
      dockerfile: ros-realsense.dockerfile
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=realsense"
    devices:
      - "/dev:/dev"
    networks:
      - ros
    restart: always
    command: roslaunch realsense2_camera rs_camera.launch

networks:
  ros:
    driver: bridge
```
