### ISSUE TITLE
D435i - IMU - linear acceleration in z without any movement

### ISSUE THREAD

**Issue by BarzelS** [realsenseai/realsense-ros#1286]
Hi,
I'm getting linear acceleration in z axis even without any movement of the camera.
Is it normal?
I think thats the reason my complementary filter drift when calculating the euler angles(rpy).

The values of z are constantly about 0.24

(The camera is steady on a table without any movement)

`rostopic echo /camera/imu : `

```
header: 
  seq: 6324
  stamp: 
    secs: 1594727089
    nsecs: 860252142
  frame_id: "camera_imu_optical_frame"
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.0
  y: -0.00349065847695
  z: 0.00174532923847
angular_velocity_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
linear_acceleration: 
  x: -0.0882598459721
  y: -9.40457725525
  z: 0.245166242123
```

rqt plot: 
![image](https://user-images.githubusercontent.com/32204244/87422403-4427e480-c5e1-11ea-8d2c-a59573671b32.png)

**Comment by MartyG-RealSense** [comment]
Hi @shirbarzel  I see from your recent case about the IMU that you have a D435i.  Have you performed a calibration on the IMU please?

The D435i's IMU hardware component does not have internal calibration.  So unless it is calibrated with an IMU calibrator tool (separate from tools used to calibrate other sensors such as depth and RGB), vertical acceleration may be unable to settle at zero even if the camera is not moving.

The calibrator tool can be found here:

https://github.com/IntelRealSense/librealsense/tree/development/tools/rs-imu-calibration#rs-imu-calibration-tool

Intel's guide to getting data from the IMU provides the following information on the subject:

https://www.intelrealsense.com/how-to-getting-imu-data-from-d435i-and-t265/

********************

The IMU sensor does not include internal calibration, which may manifest itself with non-zero angular velocities produced at idle mode and the gravity (accel) force measured being not equal to 9.80665 m/s2. 

For D435i the IMU sensor is not calibrated, hence a free calibration tool is available as as part of the SDK. 
 Running the calibration routine will calculate IMU intrinsic covariance and zero offsets, and then store them on device’s NVRAM for later use in SDK. 

The depth<->IMU sensor extrinsic (rigid body transformation) is precalculated based on mechanical drawings and cannot be modified.  When initialized, the SDK will query the device for the existence of the IMU calibration data, and if present – apply it to the raw IMU samples produced by the device.

**Comment by BarzelS** [comment]
I already perform the calibration using the rs-imu-calibrtation-tool a month ago.
But I can try it again.
Just to understand, does values like this:
```
linear_acceleration: 
  x: -0.0882598459721
  y: -9.40457725525
  z: 0.245166242123
```
While no movement on the table are normal? or do i expect to get 0.0 in the z acceleration after the calibration?

Thanks @MartyG-RealSense!

**Comment by MartyG-RealSense** [comment]
Ideally, you want Y to be as close to 9.8 as possible (the value of the Earth's gravity).  I recall though that some people have had values of around 9.4 even after IMU calibration.  RealSense programs that can make use of motion correction can adjust the raw IMU value though so that it is closer to 9.8.  

Please see the linked-to comment below and the comment below it.

https://github.com/IntelRealSense/librealsense/issues/4751#issuecomment-526344423

**Comment by BarzelS** [comment]
> Ideally, you want Y to be as close to 9.8 as possible (the value of the Earth's gravity). I recall though that some people have had values of around 9.4 even after IMU calibration. RealSense programs that can make use of motion correction can adjust the raw IMU value though so that it is closer to 9.8.
> 
> Please see the linked-to comment below and the comment below it.
> 
> [IntelRealSense/librealsense#4751 (comment)](https://github.com/IntelRealSense/librealsense/issues/4751#issuecomment-526344423)

1. I was trying to calibrate using the rs-calibration-imu.py and got this message:

```
Writing calibration to device.

Error: failed to set power state
Segmentation fault (core dumped)

```

Any idea why?

2. You answered me regarding the acceleration in Y axis but what about Z axis? what to expect?

**Comment by MartyG-RealSense** [comment]
1.  I have only seen one case where the **failed to set power state** error appeared as a result of trying to write the IMU calibration result to eeprom, and an investigation didn't find a solution for it, unfortunately.

https://github.com/IntelRealSense/librealsense/issues/6370

Do you have another computer that you can try the calibration on, please?  As the result is stored inside the camera, a successfully completed calibration should be carried back to any other computer that you plug the camera into.

2.  For comparison I laid my uncalibrated-IMU D435i on a flat surface and tested the accel values to give you some values to compare to your own.  

![image](https://user-images.githubusercontent.com/41145062/87434423-61a97e00-c5e2-11ea-88c2-0ac781345126.png)

On average I got 0.2 to 0.4 for Z accel when placing the D435i on a range of flat surfaces, but never absolute zero.

**Comment by BarzelS** [comment]
> 1. I have only seen one case where the **failed to set power state** error appeared as a result of trying to write the IMU calibration result to eeprom, and an investigation didn't find a solution for it, unfortunately.
> 
> [IntelRealSense/librealsense#6370](https://github.com/IntelRealSense/librealsense/issues/6370)
> 
> Do you have another computer that you can try the calibration on, please? As the result is stored inside the camera, a successfully completed calibration should be carried back to any other computer that you plug the camera into.
> 
> 1. For comparison I laid my uncalibrated-IMU D435i on a flat surface and tested the accel values to give you some values to compare to your own.
> 
> ![image](https://user-images.githubusercontent.com/41145062/87434423-61a97e00-c5e2-11ea-88c2-0ac781345126.png)
> 
> On average I got 0.2 to 0.4 for Z accel when placing the D435i on a range of flat surfaces, but never absolute zero.

1. I hope I managed to fix it with a different computer, at the end it wrote:
```
Writing calibration to device.
  Device PID:  0B3A
  Device name:  Intel RealSense D435I
  Serial number:  845112070914
  Firmware version:  05.12.06.00
SUCCESS: saved calibration to camera.
Done.
Segmentation fault (core dumped)

```
So I hope it actually success even tough there was a segmentation fault

2. Now I'm still getting this values:

```
angular_velocity: 
  x: 2.81880511466e-05
  y: 7.24156052456e-05
  z: 1.14160184239e-06
angular_velocity_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
linear_acceleration: 
  x: 0.345232009888
  y: -9.79773902893
  z: 0.230222553015

```

You said your values were with an uncalibrated-IMU D435i  what are the values for a calibrated IMU?

3. BTW, I have just checked the rs-motion and I'm not getting any yaw while doing yaw rotation to my camera, is it related?
