### ISSUE TITLE
Cannot set the use_sim_time parameter on the realsense2_node node.

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#1391]
I started a simulation for a robot in an empty world and wanted to test my navigation obstacle detection using ```VoxelLayer``` plugin (nav2 stack) with the Realsense D435i camera.

However, despite passing the ```use_sim_time:=True``` parameter, the msgs still have epoch stamp.

```ros2 run realsense2_node realsense2_node use_sim_time:=True```

The above command still uses system clock to give epoch time stamp on the published topics.

**Comment by ghost** [comment]
More info on the same:

My launch file where I start gazebo as well as the realsense node:

```
def generate_launch_description():
    use_sim_time = LaunchConfiguration('use_sim_time', default='true')
    world_file_name = 'picker_empty/' + 'empty.world'
    world = os.path.join(get_package_share_directory('turtlebot3_gazebo'), 'worlds', world_file_name)
    launch_file_dir = os.path.join(get_package_share_directory('picker'), 'launch')
    lidar_launch_file_dir = os.path.join(get_package_share_directory('rplidar_ros'), 'launch')
    realsense_launch_file_dir = os.path.join(get_package_share_directory('realsense2_camera'), 'launch')

    return LaunchDescription([
        ExecuteProcess(
            cmd=['gazebo', '--verbose', world, '-s', 'libgazebo_ros_init.so'],
            output='screen'),
            
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource([launch_file_dir, '/picker_state_publisher.launch.py']),
            launch_arguments={'use_sim_time': use_sim_time}.items(),
        ),
        
	IncludeLaunchDescription(
	    PythonLaunchDescriptionSource([lidar_launch_file_dir, '/rplidar.launch.py']),
	),
	
	IncludeLaunchDescription(
	    PythonLaunchDescriptionSource([realsense_launch_file_dir, '/rs.launch.py']),
	),
  
    ])
```


My rs.launch.py file:

```
def generate_launch_description():

    config = os.path.join(
        get_package_share_directory('realsense2_camera'),
        'config',
        'd435i.yaml'
        )

    return LaunchDescription([
        # Realsense
        launch_ros.actions.Node(
            package='realsense2_node',
            executable='realsense2_node',
            name='realsense2_node',
            namespace='camera',
            parameters = [{
                           'enable_pointcloud': True,
                           'use_sim_time': True,
                           'enable_gyro': False,
                           'enable_infra': False,
                           'enable_infra1': False,
                           'enable_infra2': False,
                           'enable_fisheye': False,
                           'enable_fisheye1': False, 
                           'enable_fisheye2': False,
                           'enable_gyro': False, 
                           'enable_accel': False,
                           }],
            output='screen',
            ),
    ])
```

```
gary@gary-desktop:~/turtlebot3_ws$ ros2 param get /camera/realsense2_node use_sim_time
Boolean value is: True
```

```
gary@gary-desktop:~/turtlebot3_ws/src/turtlebot3/realsense-ros$ ros2 topic echo /camera/color/image_raw
---
header:
  stamp:
    sec: 1600259625
    nanosec: 607024846
  frame_id: camera_color_optical_frame
height: 480
width: 640
encoding: rgb8
is_bigendian: 0
step: 1920
data:
- 129
- 118
- 95
- 126
- 115
- 92
- 122
- 116
- 92
- 123
- 117
- 93
- 118
- 116
- 97
- 118
- 116
- 97
- 126
- 115
- 106
- 131
- 120
- 111
- 131
- 120
- 111
- 127
- 116
- 107
- 127
- 116
- 107
- 128
- 117
- 108
- 133
- 119
- 104
- 131
- 117
- 102
- 123
- 115
- 103
- 124
- 116
- 104
- 122
- 122
- 116
- 120
- 120
- 114
- 118
- 118
- 118
- 112
- 112
- 112
- 115
- 115
- 111
- 119
- 119
- 115
- 126
- 115
- 108
- 125
- 114
- 107
- 133
- 114
- 99
- 131
- 112
- 97
- 131
- 114
- 96
- 131
- 114
- 96
- 127
- 118
- 97
- 125
- 116
- 95
- 124
- 117
- 100
- 123
- 116
- 99
- 113
- 118
- 106
- 112
- 117
- 105
- 115
- 121
- 102
- 117
- 123
- 104
- 126
- 117
- 98
- 119
- 110
- 91
- 126
- 110
- 105
- 126
- 110
- 105
- 132
- 109
- 106
- 136
- 113
- 110
- 136
- 118
- '...'
```
The stamp in the message header is still in epoch.
