### ISSUE TITLE
Support for dynamic reconfigure of filters parameter

### ISSUE THREAD

**Issue by steviedale** [realsenseai/realsense-ros#1476]
Is there a way to dynamically change the ```filters``` parameter? It looks like this is currently not supported. I was wondering if there is a known workaround for this? 

Essentially my team wants to keep the same realsense2_camera node running for several tasks. However, we need to reconfigure different parameters for each task, one of which is the ```filters``` parameter.

**Comment by MartyG-RealSense** [comment]
Hi @steviedale   You can define the filters that you want to use in the roslaunch statement and then configure specific values for parameters supported for that filter after that.  

Each parameter that can be set as a rosparam inside the launch file can also be set with dynamic reconfigure and vice versa.  The same parameter name is used for both.  Further details can be found in the link below.

https://github.com/IntelRealSense/realsense-ros/issues/1325

**Comment by steviedale** [comment]
@MartyG-RealSense Thank you for your response, that is very helpful.

Follow up question: How would I disable a filter? For example, for one task I want to use the Decimate filter and in another task, I do not. I was hoping there would be an ```enable``` parameter, but all I see are the following parameters:
```
config: 
  bools: []
  ints: 
    - 
      name: "frames_queue_size"
      value: 16
    - 
      name: "filter_magnitude"
      value: 2
    - 
      name: "stream_filter"
      value: 1
    - 
      name: "stream_format_filter"
      value: 1
    - 
      name: "stream_index_filter"
      value: -1
  strs: []
  doubles: []
  groups: 
    - 
      name: "Default"
      state: True
      id: 0
      parent: 0
```
