### ISSUE TITLE
Control "/camera/depth/color/points" rate (ROS2)

### ISSUE THREAD

**Issue by BarzelS** [realsenseai/realsense-ros#1567]
Hi,
I'm using realsense ros with D435i in ROS2.
Currently when setting:
```
        depth_fps: 30.0
        depth_height: 240
        depth_width: 424
```
The rate of the topic "/camera/depth/color/points" is ~10Hz.
(Tested using: ros2 topic hz /camera/depth/color/points)
The same configuration in ROS1 provided 30hz
Is there a way to increase the rate?
Thanks

**Comment by MartyG-RealSense** [comment]
Hi @SBarzz   Could you provide information about your configuration please:

-  Computer / computing device
- Operating system and version (e.g Ubuntu 20.04)
-  ROS2 version (Dashing, Eloquent, Foxy, etc)
-  Librealsense SDK version

Also, can you confirm please that you are using the **ROS2 Eloquent** wrapper.

https://github.com/IntelRealSense/realsense-ros/tree/eloquent

I ask this because there is an older ROS2 wrapper for RealSense that is no longer supported.

https://github.com/intel/ros2_intel_realsense

**Comment by BarzelS** [comment]
> Hi @SBarzz Could you provide information about your configuration please:
> 
> * Computer / computing device
> * Operating system and version (e.g Ubuntu 20.04)
> * ROS2 version (Dashing, Eloquent, Foxy, etc)
> * Librealsense SDK version
> 
> Also, can you confirm please that you are using the **ROS2 Eloquent** wrapper.
> 
> https://github.com/IntelRealSense/realsense-ros/tree/eloquent
> 
> I ask this because there is an older ROS2 wrapper for RealSense that is no longer supported.
> 
> https://github.com/intel/ros2_intel_realsense

Computer / computing device: Both on Dell G5 and Jetson TX2
Operating system and version: Ubuntu 18.04
ROS2 version: Eloquent
Librealsense SDK version: 
RealSense ROS v3.1.1 - ROS2 Eloquent (From this repository)
LibRealSense v2.40.0

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @SBarzz  It is important to match the RealSense ROS wrapper version as closely as possible with the librealsense SDK recommended for that particular wrapper.  The release notes for ROS2 Eloquent wrapper 3.1.1 recommend librealsense **2.38.1** instead of the more recent 2.40.0 that you are using.

The recently released ROS2 Eloquent wrapper **3.1.2** supports SDK 2.40.0.  I would recommend rebuilding the ROS2 wrapper using the 3.1.2 version.

https://github.com/IntelRealSense/realsense-ros/releases/tag/3.1.2

**Comment by BarzelS** [comment]
> Hi @SBarzz It is important to match the RealSense ROS wrapper version as closely as possible with the librealsense SDK recommended for that particular wrapper. The release notes for ROS2 Eloquent wrapper 3.1.1 recommend librealsense **2.38.1** instead of the more recent 2.40.0 that you are using.
> 
> The recently released ROS2 Eloquent wrapper **3.1.2** supports SDK 2.40.0. I would recommend rebuilding the ROS2 wrapper using the 3.1.2 version.
> 
> https://github.com/IntelRealSense/realsense-ros/releases/tag/3.1.2

Upgraded to 3.1.2 with librealsense v2.40.0
But still the rate of "/camera/depth/color/points" is slower then ROS1:
See this image:

![image](https://user-images.githubusercontent.com/32204244/102252059-471b5e00-3f0e-11eb-949b-c5f816142bea.png)

**Comment by doronhi** [comment]
I also see that `ros2 topic hz` gives a lower rate than expected.
This [answers.ros.org issue](https://answers.ros.org/question/350753/ros2-topic-hz-provides-wrong-rate-for-larger-msgs/) may be relevant.
I added a script to check the rate of arriving messages in #1571.
Running it using `./topic_hz.py /camera/depth/color/points` I get the expected 30Hz.

**Comment by BarzelS** [comment]
> I also see that `ros2 topic hz` gives a lower rate than expected.
> This [answers.ros.org issue](https://answers.ros.org/question/350753/ros2-topic-hz-provides-wrong-rate-for-larger-msgs/) may be relevant.
> I added a script to check the rate of arriving messages in #1571.
> Running it using `./topic_hz.py /camera/depth/color/points` I get the expected 30Hz.

Hi,
I used your script in order to check the rate.
The first measurement does start from 30 Hz but immediately after a few seconds the rate drops and stabilizes at 16 Hz.

![image](https://user-images.githubusercontent.com/32204244/102320715-5d183580-3f85-11eb-8bb3-08eba502c21d.png)

I don't think the problem is in the measurement of "ros2 topic" because I see that there is an effect on the rates of algorithms that receive this data as input.

Btw,
These are the parameters I use

```
camera:
    camera:
      ros__parameters:
        device_type: ''
        serial_no: ''
        usb_port_id: ''
        
        align_depth: true
        initial_reset: true

        color_fps: 30.0
        color_height: 240
        color_width: 424

        depth_fps: 30.0
        depth_height: 240
        depth_width: 424
        
        infra_fps: 30.0
        infra_height: 240
        infra_width: 424

        gyro_fps: 400.0
        accel_fps: 250.0

        enable_accel: true
        enable_color: true
        enable_depth: true
        enable_gyro: true
        enable_infra1: false
        enable_infra2: false

        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR

        stereo_module:
          emitter_enabled: 1
        unite_imu_method: 'linear_interpolation'

        rosbag_filename: ''

```
