### ISSUE TITLE
parameters in config file ignored

### ISSUE THREAD

**Issue by AndreasAZiegler** [realsenseai/realsense-ros#1640]
I'm running an Ubuntu 18.04 with ROS2 eloquent installed and use the eloquent branch of this ros driver.

When I want start the node with (how I used to do it with the previous unofficial ROS2 driver)
```
ros2 run realsense2_camera realsense2_camera_node --params-file `ros2 pkg prefix safety-field-intrusion-detector-ros`/share/safety-field-intrusion-detector-ros/config/d435i_new.yaml -r __ns:=/realsense1
```
with ```cat `ros2 pkg prefix safety-field-intrusion-detector-ros`/share/safety-field-intrusion-detector-ros/config/d435i_new.yaml```
```
realsense1:
  camera:
    ros__parameters:
        serial_no: '841512070768' # d435i
        initial_reset: true
        base_frame_id: d435i_link

        align_depth: false
        enable_pointcloud: false
        enable_fisheye: false
        enable_fisheye1: false
        enable_fisheye2: false
        enable_pose: false

        enable_color: true
        color_fps: 30.0
        color_height: 480
        color_width: 640
            
        enable_depth: true
        depth_fps: 30.0
        depth_height: 720
        depth_width: 1280

        enable_infra: false
        enable_infra1: false
        enable_infra2: false

        enable_gyro: false

        enable_accel: false
```

The node starts without considering the ```serial_no``` in the config file.

When I start the node with
```
ros2 run realsense2_camera realsense2_camera_node --params-file `ros2 pkg prefix safety-field-intrusion-detector-ros`/share/safety-field-intrusion-detector-ros/config/d435i_new.yaml -r __ns:=/realsense1 --ros-args -p serial_no:=_841512070768
```
the serial given in the terminal is taken. How can I use the parameters in a yaml-config file?
