### ISSUE TITLE
Heavier CPU usage compared to "old" ROS2 RealSense driver

### ISSUE THREAD

**Issue by AndreasAZiegler** [realsenseai/realsense-ros#1699]
I'm on the way to move from the "old" ROS2 RealSense driver (https://github.com/intel/ros2_intel_realsense/tree/refactor) to this one. I have a ROS2 node that subscribes to the depth map and the color image of two RealSense cameras/nodes. I use a ```message_filters::TimeSynchronizer<sensor_msgs::msg::Image, sensor_msgs::msg::Image>``` to synchronize the color image and the depth map. After I saw that my ROS2 node complained that it didn't receive images (color and depth) for some time, I had a look at the CPU usage. I observed that this new ROS2 driver uses quite a bit more of CPU on the UP2 board I'm using.

```htop``` on this ("new") ROS2 RealSense driver
![realsense-new](https://user-images.githubusercontent.com/6949508/107948171-c6bbbc80-6f93-11eb-9651-5a441d0351c9.png)

```htop``` on the ("old") ROS2 RealSense driver
![realsense-old](https://user-images.githubusercontent.com/6949508/107948233-dd621380-6f93-11eb-8202-1fb3550e8583.png)

I disabled some topics on the "new" ROS2 RealSense driver. This is ```ros2 topic list```
![realsense-new-topics](https://user-images.githubusercontent.com/6949508/107948391-0b475800-6f94-11eb-8b76-4567a5098b5f.png)

The same ```ros2 topic list``` with the "old" ROS2 RealSense driver
![realsense-old-topics](https://user-images.githubusercontent.com/6949508/107948429-1a2e0a80-6f94-11eb-977e-ae50fb68a1bb.png)

Do you know, where this performance difference is coming from? On a rather constrained UP2 board this makes a difference. One thought I had is to put all the tree nodes (2x RealSense and 1x my custom node) into a Component in a launch file (I didn't manage to do this yet) so that inter-process communication could be possible? But the last time I checked ```message_filters::TimeSynchronizer``` did not support inter-process communication (https://github.com/ros2/message_filters/issues/31). Do you have any ideas/hints?

**Comment by doronhi** [comment]
As the UP2 board is not available for me at the moment I used a much more powerful VM to compare. 
I also used RViz to show both color and depth images.
I also used `top` instead of `htop` as it was easier for me when the usage is summarized in one line.
I saw the opposite of what you describe:
Running with "old" wrapper:
```
  37681 doronhi   20   0 1290556 171128  65680 S 136.9   2.1   1:49.11 realsense_ros2_                                                                                    
  37716 doronhi   20   0 1492332 178340 119756 S  22.9   2.2   0:14.88 rviz2        
```

Running with "new" wrapper:
```
  37716 doronhi   20   0 1491616 175420 119804 S  21.9   2.2   0:28.72 rviz2                                                                                              
  37771 doronhi   20   0 1706164 104852  68412 S  14.6   1.3   0:14.69 realsense2_came  
```
Could it be that you are not using the same build of librealsense2 in your comparison?

**Comment by AndreasAZiegler** [comment]
In the comparison I did, I did not change the librealsense2. I was using version ```2.41.0-0~realsense0.3962```. I now updated it (```sudo apt update; sudo apt upgrade```) and realized that the new version is ```(2.42.0-0~realsense0.4059``` while the recommended version for ROS2 eloquent is ```v2.40.0``` as stated [here](https://github.com/IntelRealSense/realsense-ros/tree/eloquent). Do I have to downgrade librealsense2 to the recommended version? If so, where do I get this "older" librealsense2 version?

**Comment by doronhi** [comment]
Try this: `sudo apt-cache madison librealsense2`
Although I don't think it would matter much if you rebuilt both realsense2_camera and realsense_ros2_camera with librealsense2 version 2.42.0

**Comment by AndreasAZiegler** [comment]
```
sudo apt-cache madison librealsense2
librealsense2 | 2.42.0-0~realsense0.4059 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.41.0-0~realsense0.3962 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.40.0-0~realsense0.3814 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.39.0-0~realsense0.3571 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.39.0-0~realsense0.3569 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.38.1-0~realsense0.3378 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.38.1-0~realsense0.3376 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.36.0-0~realsense0.3169 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.2-0~realsense0.3083 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.2-0~realsense0.3077 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.2-0~realsense0.3075 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.2-0~realsense0.2994 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.2-0~realsense0.2932 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2750 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2740 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2738 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2734 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2729 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2723 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2711 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2709 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2707 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2701 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2689 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2676 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2672 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2670 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2666 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2664 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2662 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2660 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2650 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2646 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.35.0-0~realsense0.2644 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2251 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2249 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2207 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2205 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2187 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2185 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.34.0-0~realsense0.2183 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.33.1-0~realsense0.2141 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.33.1-0~realsense0.2079 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.33.1-0~realsense0.2067 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.33.1-0~realsense0.2044 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.33.1-0~realsense0.2036 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.32.1-0~realsense0.1913 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.31.0-0~realsense0.1791 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.30.0-0~realsense0.1694 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.30.0-0~realsense0.1682 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.29.0-0~realsense0.1580 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.28.1-0~realsense0.1554 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.28.1-0~realsense0.1552 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.28.0-0~realsense0.1512 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.27.0-0~realsense0.1462 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.26.0-0~realsense0.1436 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.26.0-0~realsense0.1432 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.25.0-0~realsense0.1361 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.25.0-0~realsense0.1332 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.24.0-0~realsense0.1316 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.24.0-0~realsense0.1274 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.24.0-0~realsense0.1244 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.24.0-0~realsense0.1240 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.23.0-0~realsense0.1166 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.22.0-0~realsense0.1106 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.22.0-0~realsense0.1104 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.21.0-0~realsense0.952 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.21.0-0~realsense0.932 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.21.0-0~realsense0.930 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.20.0-0~realsense0.832 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.20.0-0~realsense0.824 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.20.0-0~realsense0.822 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.20.0-0~realsense0.818 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.2-0~realsense0.808 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.2-0~realsense0.802 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.2-0~realsense0.800 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.2-0~realsense0.776 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.1-0~realsense0.642 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.1-0~realsense0.631 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.19.0-0~realsense0.615 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.18.1-0~realsense0.601 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.18.1-0~realsense0.573 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.18.1-0~realsense0.569 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.18.1-0~realsense0.567 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.18.0-0~realsense0.507 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.17.1-0~realsense0.373 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.17.1-0~realsense0.371 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.17.0-0~realsense0.281 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.17.0-0~realsense0.257 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.5-0~realsense0.209 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.5-0~realsense0.207 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.4-0~realsense0.193 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.4-0~realsense0.128 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.3-0~realsense0.116 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.3-0~realsense0.104 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.3-0~realsense0.98 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.3-0~realsense0.96 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.2-0~realsense0.73 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.2-0~realsense0.71 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.1-0~realsense0.51 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
librealsense2 | 2.16.1-0~realsense0.42 | http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic/main amd64 Packages
```

**Comment by doronhi** [comment]
`sudo apt-cache madison librealsense2` just gives you the list of available versions of the package.
to install use this:
`sudo apt-get install librealsense2=2.41.0-0~realsense0.3962`

**Comment by AndreasAZiegler** [comment]
I now installed ```librealsense2=2.40.0-0~realsense0.3814``` (the official version for ROS2 Eloquent), built the whole ROS2 workspace again and get this results (this time also with ```top```)

Old wrapper:
```
20993 mtr       20   0 1819688  84180  53976 S  32.6  1.1   0:00.43 realsense_node           
20991 mtr       20   0 1262584  81896  53224 S  29.5  1.0   0:00.39 realsense_node
```
New wrapper:
```
27384 mtr       20   0 1418044 149928  53436 S  84.7  1.9   0:15.23 realsense2_came          
27370 mtr       20   0 1377060 147256  53516 S  73.8  1.9   0:20.24 realsense2_came
```

For the old wrapper I'm using the following configs:
For the D435:
```
/realsense1:
  camera:
    ros__parameters:
        serial_no: 825312073597 # d435
        base_frame_id: d435_link
        align_depth: true
        enable_pointcloud: false
        dense_pointcloud: false
        color0:
            enabled: true
            resolution: [640,480]
            fps: 30
        depth0:
            enabled: true
            resolution: [640,480]
            fps: 30
        infra1:
            enabled: false
            resolution: [640,480]
            fps: 30
        infra2:
            enabled: false
            resolution: [640,480]
            fps: 30
```
For the D435i:
```
/realsense2:
  camera:
    ros__parameters:
        serial_no: 841512070768 # d435i
        base_frame_id: d435i_link
        align_depth: true
        enable_pointcloud: false
        dense_pointcloud: false
        color0:
            enabled: true
            resolution: [640,480]
            fps: 30
        depth0:
            enabled: true
            resolution: [640,480]
            fps: 30
        infra1:
            enabled: false
            resolution: [640,480]
            fps: 30
        infra2:
            enabled: false
            resolution: [640,480]
            fps: 30
        accel0:
            enabled: true
        gyro0:
            enabled: true
```
For the new wrapper I'm using the following configs:
For the D435:
```
realsense1:
  camera:
    ros__parameters:
        serial_no: '_825312073597' # d435
        initial_reset: true
        base_frame_id: d435_link

        align_depth: true
        enable_sync: true
        enable_pointcloud: false
        enable_fisheye: false
        enable_fisheye1: false
        enable_fisheye2: false

        enable_color: true
        color_fps: 30.0
        color_height: 720
        color_width: 1280
            
        enable_depth: true
        depth_fps: 30.0
        depth_height: 720
        depth_width: 1280

        enable_infra: false
        enable_infra1: false
        enable_infra2: false
```
For the D435i:
```
realsense2:
  camera:
    ros__parameters:
        serial_no: '_841512070768' # d435i
        initial_reset: true
        base_frame_id: d435i_link

        align_depth: true
        enable_sync: true
        enable_pointcloud: false
        enable_fisheye: false
        enable_fisheye1: false
        enable_fisheye2: false
        enable_pose: false

        enable_color: true
        color_fps: 30.0
        color_height: 720
        color_width: 1280
            
        enable_depth: true
        depth_fps: 30.0
        depth_height: 720
        depth_width: 1280

        enable_infra: false
        enable_infra1: false
        enable_infra2: false

        enable_gyro: false

        enable_accel: false
```
