### ISSUE TITLE
How to run muliple cameras with a config file

### ISSUE THREAD

**Issue by j-corvo** [realsenseai/realsense-ros#2051]
Hello,

I'm trying to launch multiple cameras (d435i and t265) together with a default config file. Considering the launch files examples, I'm using the rs_d400_and_t256_launch.py file as a reference. 

To launch the configuration file I just added the line 

`{'name': 'config_file', 'default': "'/home/rythm/dev2_ws/install/realsense2_camera/share/realsense2_camera/config/config.yaml'",'description': 'yaml config file'}`
to the local parameters as followed:

```
local_parameters = [{'name': 'camera_name1', 'default': 'd435i', 'description': 'camera unique name'},
                    {'name': 'device_type1', 'default': 'd435i', 'description': 'choose device by type'},
                    {'name': 'camera_name2', 'default': 't265', 'description': 'camera unique name'},
                    {'name': 'device_type2', 'default': 't265', 'description': 'choose device by type'},
                    `{'name': 'config_file', 'default': "'/home/rythm/dev2_ws/install/realsense2_camera/share/realsense2_camera/config/config.yaml'",'description': 'yaml config file'}`
                   ]
```

And my config.yaml file is structured as follows:

```
camera:
    camera:
      ros__parameters:
        device_type: 'd435i'
        serial_no: '048122072440'
        usb_port_id: ''

        color_fps: 30.0
        color_height: 480
        color_width: 640
        color_qos: "SENSOR_DATA"

        depth_fps: 30.0
        depth_height: 720
        depth_width: 1280
        depth_qos: "SENSOR_DATA"

        infra_height: 720
        infra_width: 1280
        infra_qos: "SENSOR_DATA"

        gyro_fps: 30.0

        enable_accel: true
        enable_color: true
        enable_depth: true
        enable_gyro: true
        enable_infra1: true
        enable_infra2: true

        enable_pointcloud: true
        filters: ''


        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR

        stereo_module:
          emitter_enabled: 1
        
        unite_imu_method: 'linear_interpolation'


camera:
    camera:
      ros__parameters:
        device_type: 't265'
        serial_no: '109422111381'
        usb_port_id: ''

        enable_fisheye1: true
        enable_fisheye2: true

        gyro_fps: 30.0

        enable_accel: true
        enable_gyro: true

        stereo_module:
          emitter_enabled: 1
        
        unite_imu_method: 'linear_interpolation'
```

It doesn't give me any error, the problem is that it appears my config file is just ignored as the topics:

/d435i/depth/color/points, 
/d435i/accel/imu_info,
/d435i/accel/sample,
/d435i/gyro/imu_info,
/d435i/gyro/sample,
/t265/accel/imu_info,
/t265/accel/sample,
/t265/gyro/imu_info,
/t265/gyro/sample,

should appear when I run the command `ros2 topic list`.

Thanks a lot for your help!

**Comment by Marenix** [comment]
First, you need to have "config_file1" and "config_file2" even if both camera use the same config file. The way it works, parameter names for each camera are different (adding 1 or 2 at the end, depending on the camera). So, your local_parameters should look something like this:
```
local_parameters = [{'name': 'camera_name1', 'default': 'd435i', 'description': 'camera unique name'},
                    {'name': 'device_type1', 'default': 'd435i', 'description': 'choose device by type'},
                    {'name': 'camera_name2', 'default': 't265', 'description': 'camera unique name'},
                    {'name': 'device_type2', 'default': 't265', 'description': 'choose device by type'},
                    {'name': 'config_file1', 'default': "'/home/rythm/dev2_ws/install/realsense2_camera/share/realsense2_camera/config/config.yaml'",'description': 'yaml config file'},
                    {'name': 'config_file2', 'default': "'/home/rythm/dev2_ws/install/realsense2_camera/share/realsense2_camera/config/config.yaml'",'description': 'yaml config file'}
]
```
I'm not 100% sure if the path like that will work or not, you'll have to try that by yourself. If it's not okay, you can also try "'/share/realsense2_cameta/config/config.yaml'".

Second thing, you have to change your config file. You use:

```
camera:
  camera:
    ros__parameters:

```
Because of that, when camera1 searches config file for it's config, it sees configs only for camera with name camera, and so it skips it. instead of that, you should use the following:

```
d435i:
    d435i:
      ros__parameters:
        device_type: 'd435i'
        serial_no: '048122072440'
        usb_port_id: ''

        color_fps: 30.0
        color_height: 480
        color_width: 640
        color_qos: "SENSOR_DATA"

        depth_fps: 30.0
        depth_height: 720
        depth_width: 1280
        depth_qos: "SENSOR_DATA"

        infra_height: 720
        infra_width: 1280
        infra_qos: "SENSOR_DATA"

        gyro_fps: 30.0

        enable_accel: true
        enable_color: true
        enable_depth: true
        enable_gyro: true
        enable_infra1: true
        enable_infra2: true

        enable_pointcloud: true
        filters: ''


        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR

        stereo_module:
          emitter_enabled: 1
        
        unite_imu_method: 'linear_interpolation'


t265:
    t265:
      ros__parameters:
        device_type: 't265'
        serial_no: '109422111381'
        usb_port_id: ''

        enable_fisheye1: true
        enable_fisheye2: true

        gyro_fps: 30.0

        enable_accel: true
        enable_gyro: true

        stereo_module:
          emitter_enabled: 1
        
        unite_imu_method: 'linear_interpolation'
```

Starting it like that, the config files should be used. I hope it work for you. Good luck!
