### ISSUE TITLE
L515 depth message has no output in ROS

### ISSUE THREAD

**Issue by rolandying** [realsenseai/realsense-ros#2226]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | L515  | 
| ROS version                     | Melodic  | 
| Firmware Version                   | 01.05.08.01 | 
| Operating System & Version |   Ubuntu18.04  | 
| Kernel Version (Linux Only)    | 5.4.0-89-generic                                        | 
| Platform                                 | PC  |
| SDK Version                            |  2.0                         | 
| Language                            |  C++/Python                        | 
|Serial No.			|     f0264437                      | 
|Product ID			|     0B64                  | 

### Issue Description
When I was running the command:
`roslaunch realsense2_camera rs_camera.launch align_depth:=true device_type:=l515 tf_prefix:=measured/camera`
Everything was fine. Both RGB and depth messages were OK, but something went wrong yesterday, I can still receive the depth message, but they are empty. To be more precise, there is no problem at the beginning, but after I run the ROS node, the above-mentioned problems will occur after a minute or so.
**I upload two videos of the whole process on youtube; they can show the problem more clearly**. Here are the links: when I run the `realsense-viewer`, [it works perfectly](https://www.youtube.com/watch?v=aiwKPmcZZ5g). 
Then I started running the ROS node, [something happened](https://www.youtube.com/watch?v=4iKQtj4jTTg). In the second video, before 1:14, the depth message is OK but with some flicker, but after that, it has just gone. 
And when I try to check the message by running the command: `rostopic echo -n1 /camera/aligned_depth_to_color/image_raw`, the output :
```
header: 
  seq: 1844
  stamp: 
    secs: 1642593577
    nsecs: 586819887
  frame_id: "measured/camera_color_optical_frame"
height: 720
width: 1280
encoding: "16UC1"
is_bigendian: 0
step: 2560
data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 153, 11, 153, 11, 153, 11, 153, 11, 153, 11, 153, 11, 153, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
```
They are all 0, too long to copy them all.

And no specific output information when an error occurs. The terminal is just keeping output the:
e, number: 61
```
 19/01 15:13:28,549 WARNING [139816150759168] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/01 15:13:29,799 WARNING [139816150759168] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/01 15:13:31,050 WARNING [139816150759168] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/01 15:13:32,301 WARNING [139816150759168] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
```
According to some replies, they can be ignored.

Every time such an error occurs, I can only temporarily solve the problem by plugging and unplugging the USB cable, because the problem will happen again after a minute.

So does someone know how to handle such things?
