### ISSUE TITLE
Ros2 depth_module.auto_exposure_enabled via launch file doesnt do anything

### ISSUE THREAD

**Issue by geoeo** [realsenseai/realsense-ros#2507]
System: Ubuntu 20.04 Ros2 Galactic

If I start the camera node via `ros2 launch realsense2_camera rs_record.py config_file:="'../my_config.yaml'"` with `depth_module.enable_auto_exposure: true`, the auto exposure is not enabled.

I can check the state of the parameter with `ros2 param get /camera/camera depth_module.enable_auto_exposure` and it returns true!

If I set it again via `ros2 param get /camera/camera depth_module.enable_auto_exposure true` then it works and the infra1 images changes exposure

**Comment by MartyG-RealSense** [comment]
Hi @geoeo  Other RealSense ROS users have tried setting the true / false status of auto_exposure or auto_exposure_priority from roslaunch instruction, launch file or yaml.  It only works when set during runtime after launch.

**ROS1**
rosrun dynamic_reconfigure dynparam set /camera/stereo_module enable_auto_exposure 1

**ROS2-DEVELOPMENT**
ros2 param set /camera/camera depth_module.enable_auto_exposure true

**Comment by geoeo** [comment]
Ok thanks for the confirmation

**Comment by geoeo** [comment]
@MartyG-RealSense Btw. This seems to be a regression as it used to work under v. 2.50

**Comment by MartyG-RealSense** [comment]
I have referred this issue to the RealSense ROS team.

**Comment by SamerKhshiboun** [comment]
Hi @geoeo,

My name is Samer, and I'm from the RealSense ROS Team.
Can you please provide me the full command of the ros2 launch cmd ?
Also, if you can provide the launch file (or paste it here).

Thanks,
Samer

**Comment by geoeo** [comment]
`ros2 launch realsense2_camera rs_launch.py config_file:="'path/to/file/launch.yaml'"`

```
camera:
    camera:
      ros__parameters:
        device_type: ''
        serial_no: ''
        usb_port_id: ''

        depth_qos: "SYSTEM_DEFAULT"
        infra_qos: "SYSTEM_DEFAULT"

        gyro_fps: 200
        accel_fps: 100

        enable_accel: true
        enable_gyro: true
        enable_depth: true
        enable_infra1: true
        enable_sync: true
        enable_color: false
        enable_infra2: false
        enable_pointcloud: false

        unite_imu_method: 1
        filters: ''

        depth_module:
            profile: 640x480x5
            emitter_enabled: 1
            align_depth: true
            enable_auto_exposure: true
            auto_exposure_limit_toggle: true
            auto_gain_limit_toggle: false
            



        rosbag_filename: ''
```
