### ISSUE TITLE
what are camera profile options for the D435i in ROS2?

### ISSUE THREAD

**Issue by patrickwasp** [realsenseai/realsense-ros#2605]
I want to try out different resolutions and framerates on a D435i and it looks like there is a way of setting them in the profile configuration. Where would I find documentation on what the options are and how I would set them up in a yaml launch file? 

These are the values I think are relevant in the `https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py` file.

       {'name': 'depth_module.profile',         'default': '0,0,0', 'description': 'depth module profile'},                           
       {'name': 'rgb_camera.profile',           'default': '0,0,0', 'description': 'color image width'},
       {'name': 'tracking_module.profile',      'default': '0,0,0', 'description': 'fisheye width'},

`test_realsense_launch.yaml`
```yaml
launch: 

- include: 
    file: "$(find-pkg-share realsense2_camera)/launch/rs_launch.py"
    arg:
    - 
        name: "depth_module.profile"
        value: ?
    - 
        name: "rgb_camera.profile"
        value: ?
    - 
        name: "tracking_module.profile"
        value: ?
```

**Comment by MartyG-RealSense** [comment]
Hi @patrickwasp  If **depth_module.profile** is set then it enables the depth stream and the infrared stream at the defined resolution.  For example, to set 640x480 resolution at 30 frames per second (FPS) speed for the depth and infrared streams:

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x30`

If **rgb_camera.profile** is set then it enables the RGB color stream at the defined resolution.   For example, to set 640x480 resolution at 30 frames per second (FPS) speed for the color stream:

`ros2 launch realsense2_camera rs_launch.py rgb_camera.profile:=640x480x30`

**tracking_module.profile** will not apply to a D435i camera model as it relates to the **fisheye** sensor that is only on the RealSense T265 Tracking Camera model.

You can look up supported resolution / FPS combinations for D435i on pages 73 and 74 of the current edition of the **D400 Series Product Family Datasheet** document at the link below.

https://dev.intelrealsense.com/docs/intel-realsense-d400-series-product-family-datasheet

https://github.com/IntelRealSense/realsense-ros/issues/1640 and https://github.com/IntelRealSense/librealsense/issues/8863 and https://github.com/IntelRealSense/realsense-ros/issues/2043#issuecomment-904345068 will hopefully be helpful references to you for setting up a **.yaml** configuration file in ROS2.

**Comment by patrickwasp** [comment]
Thank you for pointing me to the documentation. 

For reference here are the options listed for the D415 & D435/D435i/D435f cameras.

Depth (Z [16 bits])
| Resolution  | Frame Rate        |
|-------------|-------------------|
| 1280 x 720  | 6, 15, 30         |
| 848 x 480   | 6, 15, 30, 60, 90 |
| 640 x 480   | 6, 15, 30, 60, 90 |
| 640 x 360   | 6, 15, 30, 60, 90 |


Color Stream from RGB camera (YUY2 [16 bits])
| Resolution   | Frame Rate     |
|--------------|----------------|
| 1920 x 1080  | 6, 15, 30      |
| 1280 x 720   | 6, 15, 30      |
| 960 x 540    | 6, 15, 30, 60  |
| 848 x 480    | 6, 15, 30, 60  |
| 640 x 480    | 6, 15, 30, 60  |
| 640 x 360    | 6, 15, 30, 60  |
| 424 x 240    | 6, 15, 30, 60  |
| 320 x 240    | 6, 30, 60      |
| 320 x 180    | 6, 30, 60      |


The default value and description for `rgb_camera.profile` is `'0,0,0'` and `color image width`. If the correct format is using `x` instead of `,` and if the profile can modify the height, width, and frame rate, should that description and default value be changed?

**Comment by MartyG-RealSense** [comment]
If you are planning to define the profiles in the **ros2 launch** instruction then you would not need to edit the launch file contents as the ros2 launch settings will override the default settings of the launch file.

**Comment by patrickwasp** [comment]
Sorry I wasn't clear about my follow up question.

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py#L24 
`{'name': 'rgb_camera.profile',           'default': '0,0,0', 'description': 'color image width'},`
describes the `"rgb_camera.profile"` as having a default value using commas instead of `x`s and has a description indicating that it would edit only the width of the color image: "color image width"



For reference this yaml launch file configuration works as expected
```
launch: 

- include: 
    file: "$(find-pkg-share realsense2_camera)/launch/rs_launch.py"
    arg:
    -
        name: "camera_name"
        value: "depth"
    -
        name: "enable_depth"
        value: "true"
    -
        name: "enable_color"
        value: "true"
    - 
        name: "rgb_camera.profile"
        value: "1280x720x6"
    - 
        name: "depth_module.profile"
        value: "848x480x6"
```
