### ISSUE TITLE
Problem with command 'ros2 launch realsense2_camera rs_launch.py'

### ISSUE THREAD

**Issue by stelmik** [realsenseai/realsense-ros#2705]
Hi,

I have problem with execution of command:

`ros2 launch realsense2_camera rs_launch.py`

I installed ROS2 Rolling on Ubuntu 22.04 with kernel 5.19.0-40-generic (the same problem exist with kernel 5.15.0-70-generic).
I compiled and installed from source Realsense SDK than I installed realsense_camera, realsense_camera_msgs and realsense2_description.
I connected camera Intel RealSense D405 (USB 3.0).

When I try to execute (I haven't changed any content of the files from above installations):

`ros2 launch realsense2_camera rs_launch.py`

it starts and finish with exit code -11. The application log is: 

```log
[INFO] [launch]: All log files can be found below /home/username/.ros/log/2023-04-21-21-20-19-040266-computer-6650
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [realsense2_camera_node-1]: process started with pid [6651]
[realsense2_camera_node-1] [INFO] [1682104820.621445674] [camera.camera]: RealSense ROS v4.51.1
[realsense2_camera_node-1] [INFO] [1682104820.621592511] [camera.camera]: Built with LibRealSense v2.53.1
[realsense2_camera_node-1] [INFO] [1682104820.621633994] [camera.camera]: Running with LibRealSense v2.53.1
[realsense2_camera_node-1] [INFO] [1682104820.671594220] [camera.camera]: Device with serial number 11456789001 was found.
[realsense2_camera_node-1] 
[realsense2_camera_node-1] [INFO] [1682104820.671651967] [camera.camera]: Device with physical ID /sys/devices/pci0000:00/0000:00:1c.7/0000:08:00.0/usb6/6-1/6-1.1/6-1.1.4/6-1.1.4.3/6-1.1.4.3:1.0/video4linux/video0 was found.
[realsense2_camera_node-1] [INFO] [1682104820.671676605] [camera.camera]: Device with name Intel RealSense D405 was found.
[realsense2_camera_node-1] [INFO] [1682104820.671975196] [camera.camera]: Device with port number 6-1.1.4.3 was found.
[realsense2_camera_node-1] [INFO] [1682104820.672010808] [camera.camera]: Device USB type: 3.2
[realsense2_camera_node-1] [INFO] [1682104820.690765433] [camera.camera]: getParameters...
[realsense2_camera_node-1] [INFO] [1682104820.691293489] [camera.camera]: JSON file is not provided
[realsense2_camera_node-1] [INFO] [1682104820.691328114] [camera.camera]: Device Name: Intel RealSense D405
[realsense2_camera_node-1] [INFO] [1682104820.691352106] [camera.camera]: Device Serial No: 11456789001
[realsense2_camera_node-1] [INFO] [1682104820.691380618] [camera.camera]: Device physical port: /sys/devices/pci0000:00/0000:00:1c.7/0000:08:00.0/usb6/6-1/6-1.1/6-1.1.4/6-1.1.4.3/6-1.1.4.3:1.0/video4linux/video0
[realsense2_camera_node-1] [INFO] [1682104820.691405010] [camera.camera]: Device FW version: 05.14.00.00
[realsense2_camera_node-1] [INFO] [1682104820.691425871] [camera.camera]: Device Product ID: 0x0B5B
[realsense2_camera_node-1] [INFO] [1682104820.691443993] [camera.camera]: Sync Mode: Off
[realsense2_camera_node-1] [WARN] [1682104820.735490732] [camera.camera]: Could not set param: depth_module.power_line_frequency with 3 Range: [0, 2]: parameter 'depth_module.power_line_frequency' could not be set: Parameter {depth_module.power_line_frequency} doesn't comply with integer range.
[realsense2_camera_node-1] [INFO] [1682104820.758175248] [camera.camera]: Set Exposure.1 to 7500
[realsense2_camera_node-1] [INFO] [1682104820.859060600] [camera.camera]: Set ROS param depth_module.profile to default: 848x480x30
[realsense2_camera_node-1] [INFO] [1682104820.928908776] [camera.camera]: Stopping Sensor: Depth Module
[ERROR] [realsense2_camera_node-1]: process has died [pid 6651, exit code -11, cmd '/opt/ros/rolling/lib/realsense2_camera/realsense2_camera_node --ros-args --log-level info --ros-args -r __node:=camera -r __ns:=/camera --params-file /tmp/launch_params_cbte4qow --params-file /tmp/launch_params_9g6ywy7z'].
```

From the last line 
`/opt/ros/rolling/lib/realsense2_camera/realsense2_camera_node --ros-args --log-level info --ros-args -r __node:=camera -r __ns:=/camera --params-file /tmp/launch_params_cbte4qow --params-file /tmp/launch_params_9g6ywy7z`
it look like it create temporary file '/tmp/launch_params_cbte4qow' with content:

```yaml
/camera/camera:
  ros__parameters:
    accel_fps: 0
    align_depth.enable: false
    allow_no_texture_points: false
    camera_name: camera
    clip_distance: -2.0
    colorizer.enable: false
    config_file: ''
    decimation_filter.enable: false
    depth_module.exposure.1: 7500
    depth_module.exposure.2: 1
    depth_module.gain.1: 16
    depth_module.gain.2: 16
    depth_module.hdr_enabled: false
    depth_module.profile: 0,0,0
    device_type: ''
    diagnostics_period: 0.0
    enable_accel: false
    enable_color: true
    enable_confidence: true
    enable_depth: true
    enable_fisheye1: true
    enable_fisheye2: true
    enable_gyro: false
    enable_infra1: false
    enable_infra2: false
    enable_pose: true
    enable_sync: false
    gyro_fps: 0
    hdr_merge.enable: false
    infra_rgb: false
    initial_reset: false
    json_file_path: ''
    linear_accel_cov: 0.01
    log_level: info
    output: screen
    pointcloud.enable: false
    pointcloud.ordered_pc: false
    pointcloud.stream_filter: 2
    pointcloud.stream_index_filter: 0
    pose_fps: 200
    reconnect_timeout: 6.0
    rgb_camera.profile: 0,0,0
    rosbag_filename: ''
    serial_no: ''
    tf_publish_rate: 0.0
    unite_imu_method: 0
    usb_port_id: ''
    wait_for_device_timeout: -1.0
```

and create file '/tmp/launch_params_9g6ywy7z' with content:

```yaml
/camera/camera:
  ros__parameters: {}
```

Maybe somebody know where the problem is and how to solve it?
Thank you for any help.
