### ISSUE TITLE
High CPU load on Ubuntu 22.04

### ISSUE THREAD

**Issue by ajtudela** [realsenseai/realsense-ros#2717]
We're moving our software from Ubuntu 20.04 to 22.04 and we notice a high cpu load on Ubuntu 22.04 with the same configuration. 
I give you more info:
* Ubuntu 22.04 with kernel 5.15 and librealsense 2.53.1
* Intel RealSense D435i with firmware 5.14.
* ROS wrapper 4.51.1

Launch using "ros2 launch realsense2-camera rs_launch.py" with the next parameters:
```
# Intel Realsense D435
realsense:
  realsense:
    ros__parameters:
      device_type: ''
      serial_no: ''
      usb_port_id: ''
      enable_accel: false
      enable_color: true
      enable_depth: true
      enable_infra1: false
      enable_infra2: false
      enable_gyro: false
      enable_pointcloud: true
      enable_sync: true
      clip_distance: 3.0
      json_file_path: ''

      # Modules
      rgb_camera:
        profile: 848x480x30
      depth_module:
        profile: 848x480x30
        emitter_enabled: 1
        enable_auto_exposure: false
        auto_exposure_limit_toggle: false
        auto_gain_limit_toggle: false
      align_depth:
        enable: true
      pointcloud:
        enable: true
        allow_no_texture_points: false
        ordered_pc: true # This will add a point in (0,0) that must be filtered.

```
Ubuntu 20.04:
![ubuntu 20 04](https://user-images.githubusercontent.com/4681902/235092632-aebb9503-5030-45ce-94ff-184aa0697381.png)

Ubuntu 22.04:
![ubuntu 22 04](https://user-images.githubusercontent.com/4681902/235092636-68aeadb1-c3eb-4425-85d7-ae7d5f4b2d49.png)
