### ISSUE TITLE
K from camera_info

### ISSUE THREAD

**Issue by monajalal** [realsenseai/realsense-ros#2935]
Should I assume the following K from D435 is already calibrated and correct? also could you please provide the format?
`K: [385.240478515625, 0.0, 319.2182922363281, 0.0, 385.240478515625, 236.77352905273438, 0.0, 0.0, 1.0]`
like what is order of f_x, f_fy, c_x, c_y, etc

```

---
root@77c9b6999e4b:/workspace# rostopic echo /camera/depth/camera_info


header: 
  seq: 202
  stamp: 
    secs: 1700595923
    nsecs:  63802242
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [385.240478515625, 0.0, 319.2182922363281, 0.0, 385.240478515625, 236.77352905273438, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [385.240478515625, 0.0, 319.2182922363281, 0.0, 0.0, 385.240478515625, 236.77352905273438, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False


```

I am trying to convert my K to the following format but I am not sure what is the order of f_x, f_y, c_x, and c_y in either one.

```
(base) mona@ada:~/BundleSDF/milk/2022-11-18-15-10-24_milk$ cat cam_K.txt 
6.153791503906250000e+02 0.000000000000000000e+00 3.147796325683593750e+02
0.000000000000000000e+00 6.153792114257812500e+02 2.366492004394531250e+02
0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00

```

thanks for any help.

**Comment by monajalal** [comment]
What further confuses me, is when I use the following topic, I get a different K

`K: [616.056884765625, 0.0, 321.5348815917969, 0.0, 616.2793579101562, 235.87950134277344, 0.0, 0.0, 1.0]`

```
root@77c9b6999e4b:/workspace# rostopic echo /camera/color/camera_info

---
header: 
  seq: 15
  stamp: 
    secs: 1700596149
    nsecs: 718137264
  frame_id: "camera_color_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [616.056884765625, 0.0, 321.5348815917969, 0.0, 616.2793579101562, 235.87950134277344, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [616.056884765625, 0.0, 321.5348815917969, 0.0, 0.0, 616.2793579101562, 235.87950134277344, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

```

so what is cam_K.txt as in BundleSDF refer to? https://github.com/NVlabs/BundleSDF
