### ISSUE TITLE
accessing both intrinsics and extrinsics for a capture

### ISSUE THREAD

**Issue by monajalal** [realsenseai/realsense-ros#2944]
For a piece of code I need access to all these items. I want to know if the followings sound correct and how to access camera intrinsics using ros realsense topics?

The code is: https://github.com/PyramidHe/PVNet/blob/master/3dome_data_generator/mask_gen.py

and in the method `read_camera_configuration` it needs `extrinsics`, `intrinsics`, and `distortion`. 

* camera extrinsics --> not sure how to acquire this from ros-realsense?
* camera intrinsics --> I believe this is intrinsics?? K: [616.056884765625, 0.0, 321.5348815917969, 0.0, 616.2793579101562, 235.87950134277344, 0.0, 0.0, 1.0]
* camera distortion --> D: [0.0, 0.0, 0.0, 0.0, 0.0]

^^ is this camera extrinsics?  or am I getting it from the wrong topic?
```
rotation: [0.9999707341194153, 0.002675577299669385, -0.007163900416344404, -0.0026810914278030396, 0.9999961256980896, -0.0007602194091305137, 0.0071618384681642056, 0.0007794042467139661, 0.9999740719795227]
translation: [0.014838425442576408, 7.110021397238597e-05, 0.00028845336055383086]
```

![Screenshot from 2023-12-04 09-09-46](https://github.com/IntelRealSense/realsense-ros/assets/1892917/c02c2849-d4a9-4b02-8690-b0ee2a8d85e9)

I get these:

```
root@186eb653e767:/workspace# rostopic echo /camera/color/camera_info 
header: 
  seq: 308
  stamp: 
    secs: 1701698575
    nsecs: 864586115
  frame_id: "camera_color_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [616.056884765625, 0.0, 321.5348815917969, 0.0, 616.2793579101562, 235.87950134277344, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [616.056884765625, 0.0, 321.5348815917969, 0.0, 0.0, 616.2793579101562, 235.87950134277344, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---

```

```
root@186eb653e767:/workspace# rostopic echo /camera/depth/camera_info 
header: 
  seq: 308
  stamp: 
    secs: 1701698342
    nsecs: 963487148
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [385.240478515625, 0.0, 319.2182922363281, 0.0, 385.240478515625, 236.77352905273438, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [385.240478515625, 0.0, 319.2182922363281, 0.0, 0.0, 385.240478515625, 236.77352905273438, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```

I also have access to this topic but I am not sure if it is fully related to what I need:

```
root@186eb653e767:/workspace# rostopic echo /camera/extrinsics/depth_to_color
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "depth_to_color_extrinsics"
rotation: [0.9999707341194153, 0.002675577299669385, -0.007163900416344404, -0.0026810914278030396, 0.9999961256980896, -0.0007602194091305137, 0.0071618384681642056, 0.0007794042467139661, 0.9999740719795227]
translation: [0.014838425442576408, 7.110021397238597e-05, 0.00028845336055383086]
---

```
