### ISSUE TITLE
set rgb_camera.exposure value in rs_launch

### ISSUE THREAD

**Issue by patrickwasp** [realsenseai/realsense-ros#3010]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D435i                   | 
| Firmware Version                   | 5.15.1                         | 
| Operating System & Version |   Ubuntu 22.04 | 
| Kernel Version (Linux Only)    |  6.1.35                                                                    | 
| Platform                                 | PC                           |
| Librealsense SDK Version       |  v2.54.1                                                   | 
| Language                               |  n/a        | 
| Segment			         |  others                             | 
| ROS Distro			         |  Humble                                   | 
| RealSense ROS Wrapper Version   |  4.54.1-1jammy                                                 | 

### Issue Description

I see that the new version of the wrapper has added the option to set the "enable_auto_exposure" value, but I don't see how I would set it to a specific value if it was set to false. Is there a corresponding argument like `rgb_camera.exposure`?

And since it seems https://github.com/IntelRealSense/realsense-ros/issues/2798 you can't set an upper limit when auto exposure is enabled, are there any suggested strategies to implement that functionality? 

```yaml
launch: 

- include: 
    file: "$(find-pkg-share realsense2_camera)/launch/rs_launch.py"
    arg:
    -
        name: "enable_color"
        value: "true"
    - 
        name: "rgb_camera.profile"
        value: "1920x1080x6"
    -
        name: "rgb_camera.enable_auto_exposure"
        value: "false"
```

**Comment by MartyG-RealSense** [comment]
Hi @patrickwasp  Yes, you should be able to set a manual RGB exposure value with `rgb_camera.exposure`

I am not aware of a method that will allow limits to be set for RGB exposure when auto-exposure is enabled, unfortunately.

**Comment by patrickwasp** [comment]
`rgb_camera.exposure` doesn't seem to change anything, can you point me to the code that reads these arguments? 

This is the launch file I use:

```yaml

launch: 

- include: 
    file: "$(find-pkg-share realsense2_camera)/launch/rs_launch.py"
    arg:
    - 
        name: "json_file_path"
        value: "$(find-pkg-prefix bringup)/config/realsense_high_accuracy.json"
    - 
        name: "initial_reset"
        value: "true"
    -
        name: "camera_name"
        value: "depth"
    -
        name: "enable_depth"
        value: "true"
    -
        name: "align_depth.enable"
        value: "true"
    -
        name: "enable_color"
        value: "true"
    - 
        name: "rgb_camera.profile"
        value: "1920x1080x6"
    -
        name: "rgb_camera.enable_auto_exposure"
        value: "false"
    -
        name: "rgb_camera.exposure"
        value: "1"
    - 
        name: "depth_module.profile"
        value: "848x480x6"
    -
        name: "enable_infra1"
        value: "false"
    -
        name: "enable_infra2"
        value: "false"
    -
        name: "infra_rgb"
        value: "false"
    - 
        name: "colorizer.enable"
        value: "false"
    -
        name: "clip_distance"
        value: "-2."
    -
        name: "enable_gyro"
        value: "true"
    - 
        name: "enable_accel"
        value: "true"
    -
        name: "enable_pose"
        value: "true"
    -
        name: "gyro_fps"
        value: "0"
    -
        name: "accel_fps"
        value: "0"
    -
        name: "pointcloud.enable"
        value: "false"
    -
        name: "pointcloud.stream_filter"
        value: "2"
    -
        name: "pointcloud.stream_index_filter"
        value: "0"
```
