### ISSUE TITLE
Wrong frame_id in /camera/camera/infra2/camera_info

### ISSUE THREAD

**Issue by vinaym815** [realsenseai/realsense-ros#3172]
| Camera Model                      D415
| ROS Distro			        Humble

### Issue Description
The frame_id on topic /camera/camera/infra2/camera_info is wrongly published as 
camera_infra1_optical_frame

**Comment by MartyG-RealSense** [comment]
Hi @vinaym815  In https://github.com/IntelRealSense/realsense-ros/pull/1242 Doronhi the RealSense ROS1 wrapper creator discusses reasons for having the right camera frame_id for infra2 be equal to that of the left camera (infra1) as this was required by some ROS packages such as StereoCameraModel

**Comment by vinaym815** [comment]
Hello @MartyG-RealSense 
If we launch the camera using 
```ros2 launch realsense2_camera rs_launch.py enable_infra1:=true enable_infra2:=true```
and echo the topic 
```ros2 topic echo /camera/camera/infra2/camera_info```
we get 
```
header:
  stamp:
    sec: 1722328243
    nanosec: 768045898
  frame_id: camera_infra1_optical_frame
...
```
The frame id should be camera_infra2_optical_frame
