### ISSUE TITLE
Angular Velocities Output goes wrong with D435i & D455 Camera

### ISSUE THREAD

**Issue by HappySamuel** [realsenseai/realsense-ros#3195]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       |  D435i / D455                           | 
| Firmware Version                   | 5.16.0.1                          | 
| Operating System & Version |  JetPack 5.1.3 (Ubuntu 20.04)  | 
| Kernel Version (Linux Only)    |  5.10.192-tegra                                                                       | 
| Platform                                 |  NVIDIA Jetson AGX Orin                           |
| Librealsense SDK Version       |  2.54.1                                                     | 
| Language                               |  ROS2        | 
| Segment			         |  Robot                             | 
| ROS Distro			         |  Humble                                           | 
| RealSense ROS Wrapper Version   |  4.54.1                                                  | 

### Issue Description
I have the realsense-ros installed following [Realsense Camera with CUDA-enabled](https://github.com/IntelRealSense/realsense-ros/issues/3188#issuecomment-2306824690) steps suggested here. However, when i tried to enable both the gyro and accel, and having the `unite_imu_method=1 / 2` , which will output the imu topic `/front_cam/imu` . Although the camera is sitting still, for the accelerations portion, they are seems OK, but the angular velocities are awful, keep dramatically jumping around. For your info, the camera is sitting still. I tried both d435i and d455 cameras, both their angular velocities are unsable at all. And this phenomenon only observed in the `realsense-ros`, while angular velocities seems just fine in the `realsense-viewer` . Here i attached the bagfiles of both 435i and d455 cameras recorded with running realsense-ros.

[d435i_rs_imu.zip](https://github.com/user-attachments/files/16809424/d435i_rs_imu.zip)

[d455_rs_imu.zip](https://github.com/user-attachments/files/16809433/d455_rs_imu.zip)

Here are the config i used for both d435i and d455 cameras. I only enable gyro and accel at the moment with else disabled. I also have enabled the `enable_motion_correction`

```
rgb_camera:
  profile: '1280x720x15'
  global_time_enabled: true
  enable_auto_exposure: true
  enable_auto_white_balance: true
  power_line_frequency: 2
color_info_qos: "SENSOR_DATA"
color_qos: "SENSOR_DATA"

depth_module:
  profile: '640x360x60'
  global_time_enabled: true
  enable_auto_exposure: true
  hdr_enabled: false
  emitter_always_on: true
  emitter_enabled: 1  #0=OFF | 1=enable laser | 2=enable laser auto
  emitter_on_off: false

infra1_qos: "SENSOR_DATA"
infra1_info_qos: "SENSOR_DATA"
infra2_qos: "SENSOR_DATA"
infra2_info_qos: "SENSOR_DATA"

motion_module:
  global_time_enabled: true
  enable_motion_correction: true
  frames_queue_size: 16
gyro_fps: 200
accel_fps: 63
unite_imu_method: 2  #0=none | 1=copy | 2=linear_interpolation

enable_color: false
enable_depth: false
enable_infra1: false
enable_infra2: false
enable_sync: false
enable_accel: true
enable_gyro: true

pointcloud:
  enable: false
  filter_magnitude: 2  #1=OFF | 2=ON
  ordered_pc: false
  pointcloud_qos: "SENSOR_DATA"

decimation_filter:
  enable: false
  filter_magnitude: 4

clip_distance: 3.0
```

Any solution for this?

Best,
Samuel
