### ISSUE TITLE
Empty pointcloud data when accelerate_gpu_with_glsl = True

### ISSUE THREAD

**Issue by edgarcamilocamacho** [realsenseai/realsense-ros#3206]
Hello

| Required Info | |
|-|-|
| Camera Model | D435i | 
| Firmware Version | 5.16.0.1 | 
| Operating System | Ubuntu 20.04.6 LTS | 
| Platform | NVIDIA Jetson Orin AGX |
| Jetpack | 5.1.1 [L4T 35.3.1] |
| Kernel Version (Linux Only) | 5.10.104-tegra | 
| Librealsense SDK Version | 2.56.1 | 
| ROS Distro | Humble | 
| RealSense ROS Wrapper Version | 4.56.1 | 

### Issue Description

When I set `accelerate_gpu_with_glsl = True` (at the begining of the execution, not dinamically), I get empty data pointcloud like:

```
header:
  stamp:
    sec: 1726699016
    nanosec: 654941162
  frame_id: camera_depth_optical_frame
height: 1
width: 0
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
is_bigendian: false
point_step: 16
row_step: 0
data: []
is_dense: true
```

But with `accelerate_gpu_with_glsl = False` it works perfectly.

Maybe I'm setting something wrong, I attach the list of ros params:

[rs-params.txt](https://github.com/user-attachments/files/17051183/rs-params.txt)

**Comment by MartyG-RealSense** [comment]
Hi @edgarcamilocamacho  In rare cases on some computers, a pointcloud will disappear when GLSL is enabled.  There is no way to predict in advance which computers will be unable to use GLSL, unfortunately.

If you are using a Jetson then the usual way to accelerate a pointcloud will be to enable the librealsense SDK's CUDA support.  This can be done by installing the Jetson version of the librealsense packages on the **installation_jetson.md** instruction page or by building from source code with the flag **-DBUILD_WITH_CUDA=ON** included in the CMake build instruction.

**Comment by edgarcamilocamacho** [comment]
So if I install `librealsense` and `realsense-ros` in the Jetson, both from apt packages, like:

* `librealsense`: https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md
![image](https://github.com/user-attachments/assets/1232c617-697f-42d1-8441-245a6a1f4c18)


* `realsense-ros`: https://github.com/IntelRealSense/realsense-ros/blob/ros2-master/README.md
![image](https://github.com/user-attachments/assets/3af1a550-244c-4654-8bc6-9d224c1221df)


I should get both of them running with GPU, right?

There is a way to identify that it's actually using the GPU?

**Comment by edgarcamilocamacho** [comment]
Following that idea I this in my Jetson container (the sumarized steps from the links I sent before):

``` bash
# apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key # adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
# add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
# apt-get install -y librealsense2-utils librealsense2-dev ros-humble-realsense2-*
```

After that I get these versions installed:
```
# apt list --installed *realsense*
Listing... Done
librealsense2-dev/focal,now 2.55.1-0~realsense.3336 arm64 [installed]
librealsense2-gl/focal,now 2.55.1-0~realsense.3336 arm64 [installed,automatic]
librealsense2-udev-rules/focal,now 2.55.1-0~realsense.3336 arm64 [installed,automatic]
librealsense2-utils/focal,now 2.55.1-0~realsense.3336 arm64 [installed]
librealsense2/focal,now 2.55.1-0~realsense.3336 arm64 [installed,automatic]
ros-humble-librealsense2/focal,now 2.54.1-1focal.20231218.194516 arm64 [installed,automatic]
ros-humble-realsense2-camera-dbgsym/focal,now 4.54.1-1focal.20231230.021252 arm64 [installed]
ros-humble-realsense2-camera-msgs-dbgsym/focal,now 4.54.1-1focal.20231229.233803 arm64 [installed]
ros-humble-realsense2-camera-msgs/focal,now 4.54.1-1focal.20231229.233803 arm64 [installed]
ros-humble-realsense2-camera/focal,now 4.54.1-1focal.20231230.021252 arm64 [installed]
ros-humble-realsense2-description/focal,now 4.54.1-1focal.20231229.234552 arm64 [installed]
```

I got `librealsense2=2.55.1` and `realsense-ros=4.54.1`, so aparently the apt packages are pointing to not compatible libraries.

**Comment by edgarcamilocamacho** [comment]
Following that idea I this in my Jetson container (the sumarized steps from the links I sent before):

``` bash
# apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key # adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
# add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
# apt-get install -y librealsense2-utils librealsense2-dev ros-humble-realsense2-*
```

After that I get these versions installed:
```
# apt list --installed *realsense*
Listing... Done
librealsense2-dev/focal,now 2.55.1-0~realsense.3336 arm64 [installed]
librealsense2-gl/focal,now 2.55.1-0~realsense.3336 arm64 [installed,automatic]
librealsense2-udev-rules/focal,now 2.55.1-0~realsense.3336 arm64 [installed,automatic]
librealsense2-utils/focal,now 2.55.1-0~realsense.3336 arm64 [installed]
librealsense2/focal,now 2.55.1-0~realsense.3336 arm64 [installed,automatic]
ros-humble-librealsense2/focal,now 2.54.1-1focal.20231218.194516 arm64 [installed,automatic]
ros-humble-realsense2-camera-dbgsym/focal,now 4.54.1-1focal.20231230.021252 arm64 [installed]
ros-humble-realsense2-camera-msgs-dbgsym/focal,now 4.54.1-1focal.20231229.233803 arm64 [installed]
ros-humble-realsense2-camera-msgs/focal,now 4.54.1-1focal.20231229.233803 arm64 [installed]
ros-humble-realsense2-camera/focal,now 4.54.1-1focal.20231230.021252 arm64 [installed]
ros-humble-realsense2-description/focal,now 4.54.1-1focal.20231229.234552 arm64 [installed]
```

I got `librealsense2=2.55.1` and `realsense-ros=4.54.1`, so aparently the apt packages are pointing to not compatible libraries.

I could install `X.54.1` in both cases but then I won't have the `accelerate_gpu_with_glsl` (or that's what I understand, because that parameters is only mentioned in the documentation from version `4.55.1`).

**Comment by edgarcamilocamacho** [comment]
Wait... seeing it closely, it installed `librealsense2` and `ros-humble-librealsense2`. The second one has the correct version, so the questions would be:

* The `ros-humble-realsense2-camera` packages would use the libraries provided by `ros-humble-librealsense2` instead of the `librealsense2` one?
* You say the `librealsense2` apt package is ready to use CUDA in the Jetson, is the package `ros-humble-librealsense2` as well?

**Comment by MartyG-RealSense** [comment]
I am not involved in the compilation and publishing of packages, so do not have advice to provide about their contents.  

As a general rule, assume that if installation is not being performed with the Jetson packages on the` installation_jetson.md` page or the JetsonHacks website's `installLibrealsense.sh` build script at the link below then the packages do not contain CUDA support.  This is because packages that will be used on desktop / laptop PCs do not need the CUDA support because it only works with Nvidia GPUs, usually the ones built onto a Jetson board.

https://github.com/JetsonHacksNano/installLibrealsense

**Comment by MartyG-RealSense** [comment]
Hi @edgarcamilocamacho  Do you have an update about this case that you can provide, please  Thanks!

**Comment by edgarcamilocamacho** [comment]
These are the steps I'm following in my dockerfile (in the Jetson). I took the steps from the scripts you told me.

``` dockerfile
# Install librealsense
RUN cd /tmp && \
    wget https://github.com/IntelRealSense/librealsense/archive/refs/tags/v2.56.1.tar.gz && \
    tar -xzf v2.56.1.tar.gz && \
    cd librealsense-2.56.1 && \
    mkdir build && \
    cd build && \
    cmake .. \
        -DBUILD_PYTHON_BINDINGS:bool=true \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DBUILD_EXAMPLES=true \
        -DCMAKE_BUILD_TYPE=release \
        -DFORCE_LIBUVC=true \
        -DFORCE_RSUSB_BACKEND=false \
        -DBUILD_WITH_CUDA:bool=true \
        && \
    make -j 10 && \
    make install && \
    cd ../.. && \
    rm -r v2.56.1.tar.gz librealsense-2.56.1/

# Install realsense-ros
RUN source /setup_env.bash && \
    mkdir -p /robot/additional_ros_packages/src && \
    cd /robot/additional_ros_packages/src && \
    git clone -b 4.56.1  https://github.com/IntelRealSense/realsense-ros.git && \
    cd /robot/additional_ros_packages && \
    colcon build --merge-install --cmake-args '-DBUILD_ACCELERATE_GPU_WITH_GLSL=ON' && \
    rm -rf src build log
```

And I still have the same problem.

I attach the complete dockerfile.

In addition this is the docker-compose configuration:

``` yaml
  cameras:

    # common
    network_mode: host
    pid: host
    privileged: true
    runtime: nvidia
    restart: unless-stopped
    # specific
    image: gary.core.cameras.cameras:jetsonorin.4.3.beta

    environment:
      # display
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - DISPLAY=:0

    env_file:
    # common
      - ./config/env/env

    volumes:
      # common
      - ./config:/robot/config
      - ./generic_persistent_data:/robot/generic_persistent_data
      - ./component_persistent_data/cameras:/robot/component_persistent_data
      # devices
      - /dev:/dev
      - /run/udev:/run/udev:ro
      # display
      - ${XDG_RUNTIME_DIR}/gdm/Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
```

[rs.dockerfile.txt](https://github.com/user-attachments/files/17166404/rs.txt)
