### ISSUE TITLE
D435 ROS topics publishing but not sending data

### ISSUE THREAD

**Issue by Jesseblair** [realsenseai/realsense-ros#3342]
Hey @MartyG-RealSense as a frequent visitor of the issues page for the ROS wrapper I've come to the conclusion that you're the man with all the answers. All of the issues I have had so far I've been able to find solutions to however I've come across a real doozy.

I need to pull data from the pointcloud and raw image topics to use in an ROS package I am working on. I had this working just fine for quite a while on a USB 2.0 cable, I picked up a 3.0 cable so I could utilize the full potential of the camera and for whatever reason cannot get data to stream to the published topics. I am not sure if changing the cable has anything to do with my issue but as far as I'm aware that is the only factor that changed when things broke so its worth mentioning. It should be noted that when I swapped back to a 2.0 cable I still have issues. 

I am able to view everything properly in the realsense viewer which I assume means its not a hardware issue. The two topics I need are /camera/camera/color/image_raw and camera/camera/depth/color/points. For whatever reason when I run `ros2 topic echo /camera/camera/color/image_raw` it either prints nothing at all or just one "frame" of data and stops. Similarly when running `ros2 topic echo camera/camera/depth/color/points` I never get any output and at the same time the terminal I launched the wrapper from throws:
`[realsense2_camera_node-1] [WARN] [1745958420.330525264] [camera.camera]: No stream match for pointcloud chosen texture Process - Color`

I have uninstalled and reinstalled librealsense2 and the ROS wrapper hoping that would fix my issue but luck was not on my side.

I have tried a plethora of different launch arguments including but not limited to enable_sync, initial_reset, enable_color, align_depth.enable, pointcloud.allow_no_texture_points and even tried setting the depth and color profiles to 640x480x30, although that seemed to cause more issues. 

Any help would be appreciated, I look forward to hearing from you.

Launch args that worked with 2.0 cable:
`ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true pointcloud.stream_filter:=2 pointcloud.stream_index_filter:=0`

Terminal output after launch:
```shell
[INFO] [launch]: All log files can be found below /home/jesse/.ros/log/2025-04-29-16-24-04-558819-jetson-11315
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [realsense2_camera_node-1]: process started with pid [11316]
[realsense2_camera_node-1] [INFO] [1745958244.979081088] [camera.camera]: RealSense ROS v4.55.1
[realsense2_camera_node-1] [INFO] [1745958244.979479278] [camera.camera]: Built with LibRealSense v2.55.1
[realsense2_camera_node-1] [INFO] [1745958244.979526960] [camera.camera]: Running with LibRealSense v2.55.1
[realsense2_camera_node-1] [INFO] [1745958245.021675691] [camera.camera]: Device with serial number 250122077816 was found.
[realsense2_camera_node-1]
[realsense2_camera_node-1] [INFO] [1745958245.021891731] [camera.camera]: Device with physical ID /sys/devices/platform/bus@0/3610000.usb/usb2/2-2/2-2:1.0/video4linux/video0 was found.
[realsense2_camera_node-1] [INFO] [1745958245.021927892] [camera.camera]: Device with name Intel RealSense D435 was found.
[realsense2_camera_node-1] [INFO] [1745958245.022333411] [camera.camera]: Device with port number 2-2 was found.
[realsense2_camera_node-1] [INFO] [1745958245.022374628] [camera.camera]: Device USB type: 3.2
[realsense2_camera_node-1] [INFO] [1745958245.022589676] [camera.camera]: getParameters...
[realsense2_camera_node-1] [INFO] [1745958245.023136127] [camera.camera]: JSON file is not provided
[realsense2_camera_node-1] [INFO] [1745958245.023178721] [camera.camera]: Device Name: Intel RealSense D435
[realsense2_camera_node-1] [INFO] [1745958245.023208258] [camera.camera]: Device Serial No: 250122077816
[realsense2_camera_node-1] [INFO] [1745958245.023232355] [camera.camera]: Device physical port: /sys/devices/platform/bus@0/3610000.usb/usb2/2-2/2-2:1.0/video4linux/video0
[realsense2_camera_node-1] [INFO] [1745958245.023255748] [camera.camera]: Device FW version: 5.16.0.1
[realsense2_camera_node-1] [INFO] [1745958245.023278436] [camera.camera]: Device Product ID: 0x0B07
[realsense2_camera_node-1] [INFO] [1745958245.023299205] [camera.camera]: Sync Mode: Off
[realsense2_camera_node-1] [INFO] [1745958245.205911301] [camera.camera]: Set ROS param depth_module.depth_profile to default: 848x480x30
[realsense2_camera_node-1] [INFO] [1745958245.207017613] [camera.camera]: Set ROS param depth_module.infra_profile to default: 848x480x30
[realsense2_camera_node-1] [WARN] [1745958245.213589783] [camera.camera]: Could not set param: rgb_camera.power_line_frequency with 3 Range: [0, 2]: parameter 'rgb_camera.power_line_frequency' could not be set: Parameter {rgb_camera.power_line_frequency} doesn't comply with integer range.
[realsense2_camera_node-1] [INFO] [1745958245.225299575] [camera.camera]: Set ROS param rgb_camera.color_profile to default: 640x480x30
[realsense2_camera_node-1] [INFO] [1745958245.244005745] [camera.camera]: Stopping Sensor: Depth Module
[realsense2_camera_node-1] [INFO] [1745958245.244659112] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1745958245.401076836] [camera.camera]: Starting Sensor: Depth Module
[realsense2_camera_node-1] [INFO] [1745958245.413000780] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 848, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1745958245.443228832] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1745958245.453594448] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1745958245.457823815] [camera.camera]: RealSense Node Is Up!
```

**Comment by MartyG-RealSense** [comment]
Hi @Jesseblair  The message `No stream match for pointcloud chosen texture Process - Color`  indicates that RGB color frames are not being reliably received, perhaps because frames are dropping.  If echoing the color topic shows that there is no data then this could explain why that message is occurring.

Does the pointcloud generate successfully if you disable the color stream and enable the Infra1 infrared stream and use the infrared image to texture the pointcloud instead by setting the filter to '1' instead of '2' ?

`ros2 launch realsense2_camera rs_launch.py enable_color:=false enable_infra1:=true pointcloud.enable:=true pointcloud.stream_filter:=1`

**Comment by Jesseblair** [comment]
Hey @MartyG-RealSense, thanks for getting back to me. Using the infrared image to texture the pointcloud gives me the same result, no data stream. I have noticed that if I monitor the pointcloud topic with echo and restart the ROS wrapper the topic will publish a few (1-3) "frames" of data then stop.

**Comment by MartyG-RealSense** [comment]
Does performance improve if you unplug the micro-sized end of the USB cable from the side of the D435 camera, turn the connector around the other way and re-insert it (the cable is two-way insertion at the micro-sized end).

**Comment by Jesseblair** [comment]
No luck, still getting the no stream match warning and occasionally it publishes one frame then hangs

**Comment by MartyG-RealSense** [comment]
And it has the same behaviour if you launch with **ros2 run** instead of ros2 launch?

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true`

**Comment by Jesseblair** [comment]
That worked!

Is there a way I can change the launch arguments with a config file using ros2 run?

I appreciate your help.

**Comment by MartyG-RealSense** [comment]
You could try creating a **yaml** configuration file containing the launch file parameters and then load in the yaml file with a command within the ros2 run instruction.

A guide and YouTube video for doing so can be found at the link below.

https://roboticsbackend.com/ros2-yaml-params/

**Comment by MartyG-RealSense** [comment]
Hi @Jesseblair  Do you require further assistance with this case, please?  Thanks!

**Comment by Jesseblair** [comment]
Hey @MartyG-RealSense I had everything running fine for a while but I'm now running into similar issues but this time on the image_raw topic. Using ros2 run to launch works fine for the point cloud data but now the rgb image data is only publishing very briefly after the node launch then hanging just like the point cloud data was previously.

**Comment by Jesseblair** [comment]
To add onto this, when I limit the color, depth, and infra feeds to 15fps they seem to all work without issue. When running at 30+ the above issues appear.

**Comment by MartyG-RealSense** [comment]
At the start of this case you bought a USB 3.0 cable.  If you are currently using the 2.0 cable again, have you tried the 3.0 one with the config that works at 15 FPS?

**Comment by Jesseblair** [comment]
I switched over to only using the 3.0 cable a while back. I'll paste my config settings below. If I change `color_profile: 640x480x15` to `640x480x30` the issues described above start happening, otherwise the node works as intended.


```
/camera/camera:
  ros__parameters:
    camera:
      color:
        image_raw:
          format: jpeg
          jpeg_quality: 95
          png_level: 3
          tiff:
            res_unit: inch
            xdpi: -1
            ydpi: -1
        depth:
          image_rect_raw:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        infra1:
          image_rect_raw:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
        infra2:
          image_rect_raw:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
    align_depth:
      enable: true
      frames_queue_size: 16
    angular_velocity_cov: 0.01
    base_frame_id: link
    camera:
      color:
        image_raw:
          enable_pub_plugins:
          - image_transport/compressedDepth
          - image_transport/compressed
          - image_transport/raw
          - image_transport/theora
      depth:
        image_rect_raw:
          enable_pub_plugins:
          - image_transport/compressedDepth
          - image_transport/compressed
          - image_transport/raw
          - image_transport/theora
      infra1:
        image_rect_raw:
          enable_pub_plugins:
          - image_transport/compressedDepth
          - image_transport/compressed
          - image_transport/raw
          - image_transport/theora
      infra2:
        image_rect_raw:
          enable_pub_plugins:
          - image_transport/compressedDepth
          - image_transport/compressed
          - image_transport/raw
          - image_transport/theora
    camera_name: camera
    clip_distance: -1.0
    color_info_qos: DEFAULT
    color_qos: SYSTEM_DEFAULT
    colorizer:
      color_scheme: 0
      enable: false
      frames_queue_size: 16
      histogram_equalization_enabled: true
      max_distance: 6.0
      min_distance: 0.0
      stream_filter: 1
      stream_format_filter: 1
      stream_index_filter: -1
      visual_preset: 0
    decimation_filter:
      enable: false
      filter_magnitude: 2
      frames_queue_size: 16
      stream_filter: 1
      stream_format_filter: 1
      stream_index_filter: -1
    depth_info_qos: DEFAULT
    depth_module:
      auto_exposure_limit: 165000
      auto_exposure_limit_toggle: false
      auto_exposure_roi:
        bottom: 479
        left: 0
        right: 847
        top: 0
      auto_gain_limit: 248
      auto_gain_limit_toggle: false
      depth_format: Z16
      depth_profile: 848x480x15
      emitter_always_on: false
      emitter_enabled: 1
      emitter_on_off: false
      enable_auto_exposure: true
      error_polling_enabled: true
      exposure: 8500
      frames_queue_size: 16
      gain: 16
      global_time_enabled: true
      hdr_enabled: false
      infra1_format: Y8
      infra2_format: Y8
      infra_profile: 848x480x15
      inter_cam_sync_mode: 0
      laser_power: 150.0
      output_trigger_enabled: false
      sequence_id: 0
      sequence_name: 0
      sequence_size: 2
      visual_preset: 0
    depth_qos: SYSTEM_DEFAULT
    device_type: ''
    diagnostics_period: 0.0
    disparity_filter:
      enable: false
    disparity_to_depth:
      enable: false
    enable_color: true
    enable_depth: true
    enable_infra1: true
    enable_infra2: true 
    enable_rgbd: true
    enable_sync: true
    filter_by_sequence_id:
      enable: false
      frames_queue_size: 16
      sequence_id: 1
    hdr_merge:
      enable: false
      frames_queue_size: 16
    hold_back_imu_for_frames: false
    hole_filling_filter:
      enable: false
      frames_queue_size: 16
      holes_fill: 1
      stream_filter: 1
      stream_format_filter: 1
      stream_index_filter: -1
    infra1_info_qos: DEFAULT
    infra1_qos: SYSTEM_DEFAULT
    infra2_info_qos: DEFAULT
    infra2_qos: SYSTEM_DEFAULT
    initial_reset: true
    json_file_path: ''
    linear_accel_cov: 0.01
    pointcloud:
      allow_no_texture_points: true
      enable: true
      filter_magnitude: 2
      frames_queue_size: 16
      ordered_pc: false
      pointcloud_qos: DEFAULT
      stream_filter: 0
      stream_format_filter: 0
      stream_index_filter: -1
    publish_tf: true
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    reconnect_timeout: 6.0
    rgb_camera:
      auto_exposure_priority: false
      auto_exposure_roi:
        bottom: 479
        left: 0
        right: 639
        top: 0
      backlight_compensation: false
      brightness: 0
      color_format: RGB8
      color_profile: 640x480x15
      contrast: 50
      enable_auto_exposure: true
      enable_auto_white_balance: true
      exposure: 166
      frames_queue_size: 16
      gain: 64
      gamma: 300
      global_time_enabled: true
      hue: 0
      saturation: 64
      sharpness: 50
      white_balance: 4600.0
    rosbag_filename: ''
    serial_no: ''
    spatial_filter:
      enable: false
      filter_magnitude: 2
      filter_smooth_alpha: 0.5
      filter_smooth_delta: 20
      frames_queue_size: 16
      holes_fill: 0
      stream_filter: 1
      stream_format_filter: 1
      stream_index_filter: -1
    temporal_filter:
      enable: false
      filter_smooth_alpha: 0.4
      filter_smooth_delta: 20
      frames_queue_size: 16
      holes_fill: 3
      stream_filter: 1
      stream_format_filter: 1
      stream_index_filter: -1
    tf_publish_rate: 0.0
    unite_imu_method: 0
    usb_port_id: ''
    use_sim_time: false
    wait_for_device_timeout: -1.0
```
