### ISSUE TITLE
Dumping the dynamic parameters and then loading them again throws exception

### ISSUE THREAD

**Issue by Kaju-Bubanja** [realsenseai/realsense-ros#879]
Saving the dynamic parameters into a file for example of the temporal filter: `rosrun dynamic_reconfigure dynparam dump /camera/temporal test.yaml` and then loading it again `rosrun dynamic_reconfigure dynparam load /camera/temporal test.yaml` throws following error:
`[ERROR] [1565078492.496547243]: Exception thrown while processing service call: Given value -1is outside valid range!
` The file looks like this:

```
!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  filter_smooth_alpha: 0.4000000059604645
  filter_smooth_delta: 20
  frames_queue_size: 16
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      filter_smooth_alpha: 0.4000000059604645
      filter_smooth_delta: 20
      frames_queue_size: 16
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      holes_fill: 3
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      stream_filter: 1
      stream_format_filter: 1
      stream_index_filter: -1
      type: ''
    state: []
  holes_fill: 3
  stream_filter: 1
  stream_format_filter: 1
  stream_index_filter: -1
state: []

```

Is there a way to set the needed dynamic parameters with rqt_reconfigure and then save them and reload them on startup?
